### ISSUE TITLE
Template Issue

### ISSUE THREAD

**Issue by danfh00** [BerkayDur/sales-tracker-hermes#2]
### Steps
- [x] Create the __
- [x] _____

### User Story
As a ___ I need to ___ so I can ____

**Comment by A-Faris** [comment]
1. ETL Workflow

i. ETL

- Extract
- Transform
- Load
- Dockerise (Lambdafy)
- ECR
- Terraform

ii. Aggregate Lambda

- Script for Email
- SES
- Dockerise (Lambdafy)
- ECR
- Terraform

iii. Provisioning Lambda

- Read from DB and Format data for ETL Lambdas
- Dockerise
- ECR
- Terraform

iv. Step Function

- Setup Step function for ETL
- Eventbridge Scheduler
- Terraform

2. Dashboard

- Streamlit Dashboard
- Subscribe Script
- Email Verification Script
- Add product Entry
- Subscribe/Add products
- Dockerise
- ECR
- Terraform

3. Product Clean-up

- Clean-up script
- Dockerise (Lambdafy)
- ECR
- Terraform

4. Database

- Create Database
- Create Database Scripts
- Seed Database (if needed)
- Terraform Database

5. Misc

- Github Action (Pylint and Pytest)
- Branch Protection
- Creating issues (first iteration)
- Roadmap
